apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    id: 1
    orgId: 1
    version: 1
    uid: "adtq9i0gsr5dsb"
    access: proxy
    url: http://prometheus:9090
    user: ""
    password: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: "POST"
    readOnly: false
