services:
  grafana:
    build: src/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - scraping_network

  prometheus:
    build: src/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/prometheus
    networks:
      - scraping_network

  scraper:
    build: src/scraper
    container_name: scraper
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - scraping_network
    env_file:
      - scraper.env

volumes:
  grafana-storage: {}
  prometheus-storage: {}

networks:
  scraping_network:
    driver: bridge