{
 "title": "Connection Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Upstream Channel Signal Tx Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "sum(scraper_upstream_channel_tx_level{channel_index=\"1\"})",
     "legendFormat": "Channel 1"
    },
    {
     "expr": "sum(scraper_upstream_channel_tx_level{channel_index=\"2\"})",
     "legendFormat": "Channel 2"
    },
    {
     "expr": "sum(scraper_upstream_channel_tx_level{channel_index=\"3\"})",
     "legendFormat": "Channel 3"
    },
    {
     "expr": "sum(scraper_upstream_channel_tx_level{channel_index=\"4\"})",
     "legendFormat": "Channel 4"
    },
    {
     "expr": "sum(scraper_upstream_channel_tx_level{channel_index=\"5\"})",
     "legendFormat": "Channel 5"
    }
   ]
  },
  {
   "title": "Downstream Channel Snr Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "max(scraper_downstream_channel_snr_level)",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(scraper_downstream_channel_snr_level)",
     "legendFormat": "Average"
    },
    {
     "expr": "min(scraper_downstream_channel_snr_level)",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Upstream Channel Bonding State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group (scraper_upstream_channel_bonding_state{} == 1) by (channel_index,state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Channel Signal Rx Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "max(scraper_downstream_channel_rx_level)",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(scraper_downstream_channel_rx_level)",
     "legendFormat": "Average"
    },
    {
     "expr": "min(scraper_downstream_channel_rx_level)",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Ongoing Operation Health",
   "type": "state-timeline",
   "description": "Describes how successful different aspects of the scraping are.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "group (scraper_scrape_operation_state{} == 1) by (operation,state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Channel Bonding State",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "group (scraper_downstream_channel_bonding_state{} == 1) by (channel_index,state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ongoing Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(scraper_scrape_count[$__rate_interval])",
     "legendFormat": "Scrapes Attempted"
    }
   ]
  }
 ]
}